"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/area_and_polygon.py
sha256:  1bbddf82707c3425af2b47bc0365e5034470610933f1dbe1738f71d83af5741b
summary: 1/1 lanelets converted, 1 roads, 1 lanes, 1 areas skipped, 1 polygons skipped
notices: 2 info(s)
    LL2ODR-I903: 1 Area(s) recognised (1 inner ring(s) also dropped); areas have no OpenDRIVE road equivalent and are not converted yet (planned as road <object> outlines)
    LL2ODR-I904: 1 standalone Polygon(s) recognised; polygons are map furniture with no OpenDRIVE road equivalent and are not converted yet (planned as road <object> outlines)

Run this file to write area_and_polygon.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/area_and_polygon.py."""
    odr = xodr.OpenDrive('area_and_polygon', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #7 ----------------------------------------
    # reference line: 1 geometry record(s), length 40 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(40.0), 0.0, 2.0, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #7 (subtype='road'), width 4 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=4.0, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.curb))
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelet_7')
    road_1.add_type(xodr.RoadType.town, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    odr.add_road(road_1)

    # Geometry is already fixed to the input coordinates, so this only derives lane links; it will not move anything.
    odr.adjust_roads_and_lanes()
    return odr


if __name__ == "__main__":
    build().write_xml('area_and_polygon.xodr')
