"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/area_and_polygon.py
sha256:  1bbddf82707c3425af2b47bc0365e5034470610933f1dbe1738f71d83af5741b
summary: 1/1 lanelets converted, 1 roads, 1 lanes, 2 objects
notices: none

Run this file to write area_and_polygon.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/area_and_polygon.py."""
    odr = xodr.OpenDrive('area_and_polygon', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #7 ----------------------------------------
    # reference line: 1 geometry record(s), length 40 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(40.0), 0.0, 2.0, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #7 (subtype='road'), width 4 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=4.0, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.curb))
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelet_7')
    road_1.add_type(xodr.RoadType.town, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    # Area #8: 8 outline corner(s)
    obj_1_0 = xodr.Object(5.0, -12.0, Type='parkingSpace', name='area_8')
    obj_1_0_outline = xodr.Outline(closed=True)
    obj_1_0_outline.add_corner(xodr.CornerRoad(0.0, 4.0, 0.0, 0.0))
    obj_1_0_outline.add_corner(xodr.CornerRoad(20.0, 4.0, 0.0, 0.0))
    obj_1_0_outline.add_corner(xodr.CornerRoad(20.0, -4.0, 0.0, 0.0))
    obj_1_0_outline.add_corner(xodr.CornerRoad(0.0, -4.0, 0.0, 0.0))
    obj_1_0_outline.add_corner(xodr.CornerRoad(7.0, 1.0, 0.0, 0.0))
    obj_1_0_outline.add_corner(xodr.CornerRoad(13.0, 1.0, 0.0, 0.0))
    obj_1_0_outline.add_corner(xodr.CornerRoad(13.0, -1.0, 0.0, 0.0))
    obj_1_0_outline.add_corner(xodr.CornerRoad(7.0, -1.0, 0.0, 0.0))
    obj_1_0.add_outline(obj_1_0_outline)
    road_1.add_object(obj_1_0)
    # Polygon #25: 3 outline corner(s)
    obj_1_1 = xodr.Object(30.0, 3.3333333333333335, Type='parkingSpace', name='polygon_25')
    obj_1_1_outline = xodr.Outline(closed=True)
    obj_1_1_outline.add_corner(xodr.CornerRoad(0.0, -1.3333333333333335, 0.0, 0.0))
    obj_1_1_outline.add_corner(xodr.CornerRoad(6.0, -1.3333333333333335, 0.0, 0.0))
    obj_1_1_outline.add_corner(xodr.CornerRoad(6.0, 2.6666666666666665, 0.0, 0.0))
    obj_1_1.add_outline(obj_1_1_outline)
    road_1.add_object(obj_1_1)
    odr.add_road(road_1)

    # No adjust_roads_and_lanes() call: geometry is already fixed to the input coordinates, and every road and lane link was resolved from the lanelet topology rather than re-derived from geometry.
    return odr


if __name__ == "__main__":
    build().write_xml('area_and_polygon.xodr')
