"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/chain.py
sha256:  cec183a3eb885db6b474646cb95062bdb1baa6ecfe0f7373a2f6bf1bda69b0d2
summary: 4/4 lanelets converted, 1 roads, 4 lanes
notices: none

Run this file to write chain.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/chain.py."""
    odr = xodr.OpenDrive('chain', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #11, #14, #17, #20 ------------------------
    # reference line: 1 geometry record(s), length 40 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(40.0), 0.0, 1.0, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #11 (subtype='road'), width 2 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=2.0, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_1_0_m1.add_link("successor", -1)
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    # lane section 1 at s = 10 m
    center_1_1 = xodr.Lane(a=0.0)
    center_1_1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_1 = xodr.LaneSection(10.0, center_1_1)
    # lane -1  <-  lanelet #14 (subtype='road'), width 2 m (constant)
    lane_1_1_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=2.0, soffset=0.0)
    lane_1_1_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_1_1_m1.add_link("predecessor", -1)
    lane_1_1_m1.add_link("successor", -1)
    ls_1_1.add_right_lane(lane_1_1_m1)
    lanes_1.add_lanesection(ls_1_1)

    # lane section 2 at s = 20 m
    center_1_2 = xodr.Lane(a=0.0)
    center_1_2.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_2 = xodr.LaneSection(20.0, center_1_2)
    # lane -1  <-  lanelet #17 (subtype='road'), width 2 m (constant)
    lane_1_2_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=2.0, soffset=0.0)
    lane_1_2_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_1_2_m1.add_link("predecessor", -1)
    lane_1_2_m1.add_link("successor", -1)
    ls_1_2.add_right_lane(lane_1_2_m1)
    lanes_1.add_lanesection(ls_1_2)

    # lane section 3 at s = 30 m
    center_1_3 = xodr.Lane(a=0.0)
    center_1_3.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_3 = xodr.LaneSection(30.0, center_1_3)
    # lane -1  <-  lanelet #20 (subtype='road'), width 2 m (constant)
    lane_1_3_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=2.0, soffset=0.0)
    lane_1_3_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_1_3_m1.add_link("predecessor", -1)
    ls_1_3.add_right_lane(lane_1_3_m1)
    lanes_1.add_lanesection(ls_1_3)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelets_11_20')
    road_1.add_type(xodr.RoadType.unknown, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    odr.add_road(road_1)

    # Geometry is already fixed to the input coordinates, so this only derives lane links; it will not move anything.
    odr.adjust_roads_and_lanes()
    return odr


if __name__ == "__main__":
    build().write_xml('chain.xodr')
