"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/curved_road.py
sha256:  cd4d9c25a2997dde0264af5ab45ccfbcb7e81873d1d76b5870083da320e95671
summary: 1/1 lanelets converted, 1 roads, 1 lanes
notices: none

Run this file to write curved_road.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/curved_road.py."""
    odr = xodr.OpenDrive('curved_road', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #29 ---------------------------------------
    # reference line: 12 geometry record(s), length 59.656 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(5.031277912114584), 38.5, 0.0, 1.6527745186248388, s=0.0)
    pv_1.add_fixed_geometry(xodr.Line(5.020378882710842), 38.088006757777215, 5.014381217786981, 1.7837100981379297, s=5.031277912114584)
    pv_1.add_fixed_geometry(xodr.Line(5.009479859800358), 37.027156674414286, 9.921396728929963, 1.9146458338022603, s=10.051656794825426)
    pv_1.add_fixed_geometry(xodr.Line(4.998580843425609), 35.33839211855672, 14.637641287964684, 2.045581726639162, s=15.061136654625784)
    pv_1.add_fixed_geometry(xodr.Line(4.98768183362945), 33.05330291110607, 19.08333333333333, 2.176517777678891, s=20.05971749805139)
    pv_1.add_fixed_geometry(xodr.Line(4.976782830455081), 30.21353970942454, 23.183664421415447, 2.3074539879607383, s=25.047399331680843)
    pv_1.add_fixed_geometry(xodr.Line(4.965883833946124), 26.870057685088806, 26.870057685088803, 2.438390358533099, s=30.024182162135922)
    pv_1.add_fixed_geometry(xodr.Line(4.954984844146544), 23.082204183247324, 30.081314152709332, 2.569326890453605, s=34.990065996082045)
    pv_1.add_fixed_geometry(xodr.Line(4.944085861100732), 18.91666666666667, 32.76462777651126, 2.700263584789209, s=39.94505084022859)
    pv_1.add_fixed_geometry(xodr.Line(4.93318688485344), 14.446299571782141, 34.87645235230107, 2.8312004426162853, s=44.88913670132932)
    pv_1.add_fixed_geometry(xodr.Line(4.922287915449812), 9.748850698861613, 36.383206123554906, 2.962137465020748, s=49.82232358618276)
    pv_1.add_fixed_geometry(xodr.Line(4.91138895293545), 4.905609390936944, 37.26180270663237, 3.093074653098142, s=54.744611501632576)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #29 (subtype='road'), 10 width record(s)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=2.9977470099040517, b=0.03184086504633349, soffset=0.0)
    lane_1_0_m1.add_lane_width(a=3.1579472509142907, b=0.03437060666911339, soffset=5.031277912114584)
    lane_1_0_m1.add_lane_width(a=3.2442239848680794, b=0.03184612659045653, soffset=7.541467353470005)
    lane_1_0_m1.add_lane_width(a=3.3241637955835115, b=0.03450948113990315, soffset=10.051656794825426)
    lane_1_0_m1.add_lane_width(a=3.410601070954764, b=0.031851666936862214, soffset=12.556396724725605)
    lane_1_0_m1.add_lane_width(a=3.490381212965404, b=0.033253096157702944, soffset=15.061136654625784)
    lane_1_0_m1.add_lane_width(a=3.82281866329931, b=0.03339909284209364, soffset=25.047399331680843)
    lane_1_0_m1.add_lane_width(a=4.155259597345388, b=0.03354637349315334, soffset=34.990065996082045)
    lane_1_0_m1.add_lane_width(a=4.487704011440024, b=0.03369495521854316, soffset=44.88913670132932)
    lane_1_0_m1.add_lane_width(a=4.820151902831414, b=0.03384485543000854, soffset=54.744611501632576)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.curb))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_id", '29'))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelet_29')
    road_1.add_type(xodr.RoadType.town, 0.0, speed=50.0, speed_unit='km/h')
    road_1.add_elevation(0.0, 0.0, 0.09937833066149514, 0.0, 0.0)
    road_1.add_elevation(5.031277912114584, 0.5, 0.09959407679804759, 0.0, 0.0)
    road_1.add_elevation(10.051656794825426, 1.0, 0.09981076159470305, 0.0, 0.0)
    road_1.add_elevation(15.061136654625784, 1.5, 0.10002839118979659, 0.0, 0.0)
    road_1.add_elevation(20.05971749805139, 2.0, 0.10024697177529435, 0.0, 0.0)
    road_1.add_elevation(25.047399331680843, 2.5, 0.10046650959738176, 0.0, 0.0)
    road_1.add_elevation(30.024182162135922, 3.0, 0.1006870109570559, 0.0, 0.0)
    road_1.add_elevation(34.990065996082045, 3.5, 0.10090848221073034, 0.0, 0.0)
    road_1.add_elevation(39.94505084022859, 4.0, 0.10113092977084383, 0.0, 0.0)
    road_1.add_elevation(44.88913670132932, 4.5, 0.10135436010648001, 0.0, 0.0)
    road_1.add_elevation(49.82232358618276, 5.0, 0.10157877974399399, 0.0, 0.0)
    road_1.add_elevation(54.744611501632576, 5.5, 0.10180419526764592, 0.0, 0.0)
    road_1.add_superelevation(0.0, 0.0, -0.0007496356299963415, 0.0, 0.0)
    road_1.add_superelevation(2.515638956057292, -0.0018858125936673468, -0.000706714771697003, 0.0, 0.0)
    road_1.add_superelevation(5.031277912114584, -0.0036636518041694628, -0.0005413581869885767, 0.0, 0.0)
    road_1.add_superelevation(7.541467353470005, -0.005022563409139502, -0.0005147797450873012, 0.0, 0.0)
    road_1.add_superelevation(10.051656794825426, -0.0063147580898812805, -0.0003591896667813683, 0.0, 0.0)
    road_1.add_superelevation(12.556396724725605, -0.007214434790676114, -0.00035287720926800205, 0.0, 0.0)
    road_1.add_superelevation(15.061136654625784, -0.00809830042708142, -0.00020816964222821364, 0.0, 0.0)
    road_1.add_superelevation(20.05971749805139, -0.00913885321290613, -8.03839499019997e-05, 0.0, 0.0)
    road_1.add_superelevation(25.047399331680843, -0.009539782779547715, 3.0971654791234775e-05, 0.0, 0.0)
    road_1.add_superelevation(30.024182162135922, -0.009385643579751916, 0.00012888885773398656, 0.0, 0.0)
    road_1.add_superelevation(34.990065996082045, -0.00874559648475493, 0.0002156901649325042, 0.0, 0.0)
    road_1.add_superelevation(39.94505084022859, -0.0076768549864829035, 0.0002930955714411956, 0.0, 0.0)
    road_1.add_superelevation(44.88913670132932, -0.006227765315769249, 0.0003623139328813774, 0.0, 0.0)
    road_1.add_superelevation(49.82232358618276, -0.004440402973879168, 0.00042413654257220204, 0.0, 0.0)
    road_1.add_superelevation(54.744611501632576, -0.002352680795875352, 0.0004790255502915061, 0.0, 0.0)
    odr.add_road(road_1)

    # No adjust_roads_and_lanes() call: geometry is already fixed to the input coordinates, and every road and lane link was resolved from the lanelet topology rather than re-derived from geometry.
    return odr


if __name__ == "__main__":
    build().write_xml('curved_road.xodr')
