"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/lane_drop.py
sha256:  05c5f6f83fe1b2e6577db10f527bd4ebf3efa1f778043785b40c867d5f864e5a
summary: 3/3 lanelets converted, 1 roads, 3 lanes
notices: none

Run this file to write lane_drop.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/lane_drop.py."""
    odr = xodr.OpenDrive('lane_drop', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #11, #13, #15 -----------------------------
    # reference line: 1 geometry record(s), length 60 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(60.0), 0.0, 3.5, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #11 (subtype='road'), width 3.5 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.5, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.broken, width=0.12, length=3.0, space=6.0))
    lane_1_0_m1.add_link("successor", -1)
    ls_1_0.add_right_lane(lane_1_0_m1)
    # lane -2  <-  lanelet #13 (subtype='road'), width 3.5 m (constant)
    lane_1_0_m2 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.5, soffset=0.0)
    lane_1_0_m2.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_0.add_right_lane(lane_1_0_m2)
    lanes_1.add_lanesection(ls_1_0)

    # lane section 1 at s = 30 m
    center_1_1 = xodr.Lane(a=0.0)
    center_1_1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_1 = xodr.LaneSection(30.0, center_1_1)
    # lane -1  <-  lanelet #15 (subtype='road'), width 3.5 m (constant)
    lane_1_1_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.5, soffset=0.0)
    lane_1_1_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_1_1_m1.add_link("predecessor", -1)
    ls_1_1.add_right_lane(lane_1_1_m1)
    lanes_1.add_lanesection(ls_1_1)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelets_11_15')
    road_1.add_type(xodr.RoadType.unknown, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    odr.add_road(road_1)

    # Geometry is already fixed to the input coordinates, so this only derives lane links; it will not move anything.
    odr.adjust_roads_and_lanes()
    return odr


if __name__ == "__main__":
    build().write_xml('lane_drop.xodr')
