"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/loads_from_file.py
sha256:  d81f8cb2ebf9ea4b6f0c16a33af1337baa682e505f173773d09218c6746df7a5
summary: 0/0 lanelets converted, 0 roads, 0 lanes
notices: 1 error(s), 1 warning(s)
    LL2ODR-E402: lanelet2.io.load() reads a map at runtime, so it cannot be resolved statically; this transpiler converts maps that the script *builds*
    LL2ODR-W504: the script produced no convertible lanelets; nothing to emit

Run this file to write loads_from_file.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/loads_from_file.py."""
    odr = xodr.OpenDrive('loads_from_file', revMajor='1', revMinor='5')

    return odr


if __name__ == "__main__":
    build().write_xml('loads_from_file.xodr')
