"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/merge.py
sha256:  8b8841b60d68d42037e48959b43f605106dbb0209317863860b5f799f95f42cc
summary: 4/4 lanelets converted, 3 roads, 4 lanes
notices: 1 warning(s), 1 info(s)
    LL2ODR-W512: road 1 and road 3 are linked through junction 1 but their reference lines are 3 m apart where they meet; the cross-section changes across the join, so each road follows a different boundary
    LL2ODR-I911: 1 of 2 reference-line handovers do not meet; choosing the reference boundary across the network instead of per road would close 1 of them, at the cost of 2 cross-section(s) moving off their leftmost boundary and 2 lane(s) changing side

Run this file to write merge.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/merge.py."""
    odr = xodr.OpenDrive('merge', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #4 ----------------------------------------
    # reference line: 1 geometry record(s), length 30 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(30.0), 0.0, 3.0, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #4 (subtype='road'), width 3 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.0, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_id", '4'))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelet_4')
    road_1.add_type(xodr.RoadType.unknown, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    road_1.add_successor(xodr.ElementType.junction, 1)
    odr.add_road(road_1)

    # ---- road 2  <-  lanelet #9 ----------------------------------------
    # reference line: 1 geometry record(s), length 30.8058 m
    pv_2 = xodr.PlanView()
    pv_2.add_fixed_geometry(xodr.Line(30.805843601498726), 0.0, 13.0, -0.22923193327699534, s=0.0)

    lanes_2 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_2_0 = xodr.Lane(a=0.0)
    center_2_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_2_0 = xodr.LaneSection(0.0, center_2_0)
    # lane -1  <-  lanelet #9 (subtype='road'), width 2.92152 m (constant)
    lane_2_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=2.92152362922538, soffset=0.0)
    lane_2_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_2_0_m1.add_userdata(xodr.UserData("lanelet2_id", '9'))
    lane_2_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_2_0.add_right_lane(lane_2_0_m1)
    lanes_2.add_lanesection(ls_2_0)

    road_2 = xodr.Road(2, pv_2, lanes_2, name='lanelet_9')
    road_2.add_type(xodr.RoadType.unknown, 0.0)
    road_2.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    road_2.add_successor(xodr.ElementType.junction, 1)
    odr.add_road(road_2)

    # ---- road 3  <-  lanelet #19, #16 ----------------------------------
    # reference line: 1 geometry record(s), length 30 m
    pv_3 = xodr.PlanView()
    pv_3.add_fixed_geometry(xodr.Line(30.0), 30.0, 6.0, 0.0, s=0.0)

    lanes_3 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_3_0 = xodr.Lane(a=0.0)
    center_3_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_3_0 = xodr.LaneSection(0.0, center_3_0)
    # lane -1  <-  lanelet #19 (subtype='road'), width 3 m (constant)
    lane_3_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.0, soffset=0.0)
    lane_3_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_3_0_m1.add_userdata(xodr.UserData("lanelet2_id", '19'))
    lane_3_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_3_0.add_right_lane(lane_3_0_m1)
    # lane -2  <-  lanelet #16 (subtype='road'), width 3 m (constant)
    lane_3_0_m2 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.0, soffset=0.0)
    lane_3_0_m2.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_3_0_m2.add_userdata(xodr.UserData("lanelet2_id", '16'))
    lane_3_0_m2.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_3_0.add_right_lane(lane_3_0_m2)
    lanes_3.add_lanesection(ls_3_0)

    road_3 = xodr.Road(3, pv_3, lanes_3, road_type=1, name='lanelets_19_16')
    road_3.add_type(xodr.RoadType.unknown, 0.0)
    road_3.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    odr.add_road(road_3)

    # ---- junction 1  (2 connection(s)) ---------------------------------
    junction_1 = xodr.Junction('junction_1', 1)
    conn_1_0 = xodr.Connection(2, 3, xodr.ContactPoint.start)
    conn_1_0.add_lanelink(-1, -1)
    junction_1.add_connection(conn_1_0)
    conn_1_1 = xodr.Connection(1, 3, xodr.ContactPoint.start)
    conn_1_1.add_lanelink(-1, -2)
    junction_1.add_connection(conn_1_1)
    odr.add_junction(junction_1)

    # No adjust_roads_and_lanes() call: geometry is already fixed to the input coordinates, and every road and lane link was resolved from the lanelet topology rather than re-derived from geometry.
    return odr


if __name__ == "__main__":
    build().write_xml('merge.xodr')
