"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/minimal.py
sha256:  6b69655d063ed60746cda61e55216a3744a28d5424b095e2067576df5cfd23bd
summary: 1/1 lanelets converted, 1 roads, 1 lanes
notices: 2 warning(s)
    LL2ODR-W501: lanelet #7: the bound named 'right' lies to the left of the bound named 'left'; using the geometric left as the reference line
    LL2ODR-W801: lanelet #7 has no 'subtype' tag; assuming lane type 'driving'

Run this file to write minimal.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/minimal.py."""
    odr = xodr.OpenDrive('minimal', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #7 ----------------------------------------
    # reference line: 1 geometry record(s), length 1 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(1.0), 0.0, 1.0, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #7, width 1 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=1.0, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelet_7')
    road_1.add_type(xodr.RoadType.unknown, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    odr.add_road(road_1)

    # No adjust_roads_and_lanes() call: geometry is already fixed to the input coordinates, and every road and lane link was resolved from the lanelet topology rather than re-derived from geometry.
    return odr


if __name__ == "__main__":
    build().write_xml('minimal.xodr')
