"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/parallel_lanes.py
sha256:  a4a8b8c4fb36277755bfe8f3aa8275b30fdb0d2c189e29a4c4f115eccfed0101
summary: 4/4 lanelets converted, 1 roads, 4 lanes
notices: none

Run this file to write parallel_lanes.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/parallel_lanes.py."""
    odr = xodr.OpenDrive('parallel_lanes', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #13, #14, #18, #19 ------------------------
    # reference line: 1 geometry record(s), length 50 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(50.0), 0.0, 3.5, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #13 (subtype='highway'), width 3.5 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.5, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.broken, width=0.12, length=3.0, space=6.0))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_id", '13'))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'highway'))
    lane_1_0_m1.add_link("successor", -1)
    ls_1_0.add_right_lane(lane_1_0_m1)
    # lane -2  <-  lanelet #14 (subtype='highway'), width 3.5 m (constant)
    lane_1_0_m2 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.5, soffset=0.0)
    lane_1_0_m2.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    lane_1_0_m2.add_userdata(xodr.UserData("lanelet2_id", '14'))
    lane_1_0_m2.add_userdata(xodr.UserData("lanelet2_subtype", 'highway'))
    lane_1_0_m2.add_link("successor", -2)
    ls_1_0.add_right_lane(lane_1_0_m2)
    lanes_1.add_lanesection(ls_1_0)

    # lane section 1 at s = 25 m
    center_1_1 = xodr.Lane(a=0.0)
    center_1_1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    ls_1_1 = xodr.LaneSection(25.0, center_1_1)
    # lane -1  <-  lanelet #18 (subtype='highway'), width 3.5 m (constant)
    lane_1_1_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.5, soffset=0.0)
    lane_1_1_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.broken, width=0.12, length=3.0, space=6.0))
    lane_1_1_m1.add_userdata(xodr.UserData("lanelet2_id", '18'))
    lane_1_1_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'highway'))
    lane_1_1_m1.add_link("predecessor", -1)
    ls_1_1.add_right_lane(lane_1_1_m1)
    # lane -2  <-  lanelet #19 (subtype='highway'), width 3.5 m (constant)
    lane_1_1_m2 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.5, soffset=0.0)
    lane_1_1_m2.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    lane_1_1_m2.add_userdata(xodr.UserData("lanelet2_id", '19'))
    lane_1_1_m2.add_userdata(xodr.UserData("lanelet2_subtype", 'highway'))
    lane_1_1_m2.add_link("predecessor", -2)
    ls_1_1.add_right_lane(lane_1_1_m2)
    lanes_1.add_lanesection(ls_1_1)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelets_13_19')
    road_1.add_type(xodr.RoadType.motorway, 0.0, speed=100.0, speed_unit='km/h')
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    odr.add_road(road_1)

    # No adjust_roads_and_lanes() call: geometry is already fixed to the input coordinates, and every road and lane link was resolved from the lanelet topology rather than re-derived from geometry.
    return odr


if __name__ == "__main__":
    build().write_xml('parallel_lanes.xodr')
