"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/right_of_way.py
sha256:  ab479f5f13c6e9d1b04fb8170c3c7cba0a85d6de519a47d8818ddf0c27e8e7f4
summary: 3/3 lanelets converted, 3 roads, 3 lanes
notices: none

Run this file to write right_of_way.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

import xml.etree.ElementTree as ET

from scenariogeneration import xodr


class _JunctionWithPriority(xodr.Junction):
    """xodr.Junction plus <priority>, which the library omits."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.priorities = []

    def get_element(self):
        element = super().get_element()
        # OpenDRIVE orders <junction> as connection*, priority*.
        for high, low in self.priorities:
            ET.SubElement(element, "priority", {"high": str(high), "low": str(low)})
        return element


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/right_of_way.py."""
    odr = xodr.OpenDrive('right_of_way', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #5 ----------------------------------------
    # reference line: 1 geometry record(s), length 30 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(30.0), 0.0, 1.5, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #5 (subtype='road'), width 3 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.0, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_id", '5'))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelet_5')
    road_1.add_type(xodr.RoadType.unknown, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    road_1.add_successor(xodr.ElementType.junction, 1)
    odr.add_road(road_1)

    # ---- road 2  <-  lanelet #8 ----------------------------------------
    # reference line: 1 geometry record(s), length 30 m
    pv_2 = xodr.PlanView()
    pv_2.add_fixed_geometry(xodr.Line(30.0), 30.0, 1.5, 0.0, s=0.0)

    lanes_2 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_2_0 = xodr.Lane(a=0.0)
    center_2_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_2_0 = xodr.LaneSection(0.0, center_2_0)
    # lane -1  <-  lanelet #8 (subtype='road'), width 3 m (constant)
    lane_2_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.0, soffset=0.0)
    lane_2_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_2_0_m1.add_userdata(xodr.UserData("lanelet2_id", '8'))
    lane_2_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_2_0.add_right_lane(lane_2_0_m1)
    lanes_2.add_lanesection(ls_2_0)

    road_2 = xodr.Road(2, pv_2, lanes_2, road_type=1, name='lanelet_8')
    road_2.add_type(xodr.RoadType.unknown, 0.0)
    road_2.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    road_2.add_predecessor(xodr.ElementType.road, 1, contact_point=xodr.ContactPoint.end)
    odr.add_road(road_2)

    # ---- road 3  <-  lanelet #13 ---------------------------------------
    # reference line: 1 geometry record(s), length 31.7844 m
    pv_3 = xodr.PlanView()
    pv_3.add_fixed_geometry(xodr.Line(31.784430150625635), 30.0, 1.5, 0.33667481938672716, s=0.0)

    lanes_3 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_3_0 = xodr.Lane(a=0.0)
    center_3_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_3_0 = xodr.LaneSection(0.0, center_3_0)
    # lane -1  <-  lanelet #13 (subtype='road'), width 2.83158 m (constant)
    lane_3_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=2.8315750690980526, soffset=0.0)
    lane_3_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_3_0_m1.add_userdata(xodr.UserData("lanelet2_id", '13'))
    lane_3_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_3_0.add_right_lane(lane_3_0_m1)
    lanes_3.add_lanesection(ls_3_0)

    road_3 = xodr.Road(3, pv_3, lanes_3, road_type=1, name='lanelet_13')
    road_3.add_type(xodr.RoadType.unknown, 0.0)
    road_3.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    road_3.add_predecessor(xodr.ElementType.road, 1, contact_point=xodr.ContactPoint.end)
    odr.add_road(road_3)

    # ---- junction 1  (2 connection(s), 1 priority record(s)) -----------
    junction_1 = _JunctionWithPriority('junction_1', 1)
    # RightOfWay #21
    junction_1.priorities.append((2, 3))
    conn_1_0 = xodr.Connection(1, 2, xodr.ContactPoint.start)
    conn_1_0.add_lanelink(-1, -1)
    junction_1.add_connection(conn_1_0)
    conn_1_1 = xodr.Connection(1, 3, xodr.ContactPoint.start)
    conn_1_1.add_lanelink(-1, -1)
    junction_1.add_connection(conn_1_1)
    odr.add_junction(junction_1)

    # No adjust_roads_and_lanes() call: geometry is already fixed to the input coordinates, and every road and lane link was resolved from the lanelet topology rather than re-derived from geometry.
    return odr


if __name__ == "__main__":
    build().write_xml('right_of_way.xodr')
