"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/street_furniture.py
sha256:  af5c69df60a5a155285be1be22262f7a6c13ef21b011ea3dea911891516d230c
summary: 2/2 lanelets converted, 1 roads, 1 lanes, 2 objects
notices: 1 info(s)
    LL2ODR-I910: 1 crosswalk lanelet(s) became <object type="crosswalk"> on the road they cross rather than roads of their own, which is how OpenDRIVE models a crossing; they are no longer routable paths

Run this file to write street_furniture.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/street_furniture.py."""
    odr = xodr.OpenDrive('street_furniture', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #8 ----------------------------------------
    # reference line: 1 geometry record(s), length 40 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(40.0), 0.0, 2.0, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #8 (subtype='road'), width 4 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=4.0, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelet_8')
    road_1.add_type(xodr.RoadType.town, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    # barrier #4: 3 outline corner(s), open, height 0.75 m assumed
    obj_1_0 = xodr.Object(0.0, -4.0, Type='barrier', name='guard_rail_4', height=0.75)
    obj_1_0_outline = xodr.Outline(closed=False)
    obj_1_0_outline.add_corner(xodr.CornerRoad(0.0, 0.0, 0.0, 0.0))
    obj_1_0_outline.add_corner(xodr.CornerRoad(20.0, 0.0, 0.0, 0.0))
    obj_1_0_outline.add_corner(xodr.CornerRoad(40.0, 0.0, 0.0, 0.0))
    obj_1_0.add_outline(obj_1_0_outline)
    road_1.add_object(obj_1_0)
    # Crosswalk #9: 4 outline corner(s)
    obj_1_1 = xodr.Object(8.0, -2.0, Type='crosswalk', name='crosswalk_9')
    obj_1_1_outline = xodr.Outline(closed=True)
    obj_1_1_outline.add_corner(xodr.CornerRoad(0.0, 5.0, 0.0, 0.0))
    obj_1_1_outline.add_corner(xodr.CornerRoad(0.0, -5.0, 0.0, 0.0))
    obj_1_1_outline.add_corner(xodr.CornerRoad(4.0, -5.0, 0.0, 0.0))
    obj_1_1_outline.add_corner(xodr.CornerRoad(4.0, 5.0, 0.0, 0.0))
    obj_1_1.add_outline(obj_1_1_outline)
    road_1.add_object(obj_1_1)
    odr.add_road(road_1)

    # No adjust_roads_and_lanes() call: geometry is already fixed to the input coordinates, and every road and lane link was resolved from the lanelet topology rather than re-derived from geometry.
    return odr


if __name__ == "__main__":
    build().write_xml('street_furniture.xodr')
