"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/two_way.py
sha256:  e5bf670b973767d516a879bd2f63385fd41240b6499d25eb39fb5f87c7e619c7
summary: 2/2 lanelets converted, 1 roads, 2 lanes
notices: 1 info(s)
    LL2ODR-I907: lanelets #13 and #14 travel in opposite directions across a shared boundary; they become one road with +/- lanes, and its reference line follows that boundary regardless of --reference-line

Run this file to write two_way.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/two_way.py."""
    odr = xodr.OpenDrive('two_way', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #14, #13 ----------------------------------
    # reference line: 1 geometry record(s), length 50 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(50.0), 0.0, 0.0, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid_solid, width=0.12))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane 1  <-  lanelet #14 (subtype='road'), width 3.5 m (constant)
    lane_1_0_p1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.5, soffset=0.0)
    lane_1_0_p1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    lane_1_0_p1.add_userdata(xodr.UserData("lanelet2_id", '14'))
    lane_1_0_p1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_1_0.add_left_lane(lane_1_0_p1)
    # lane -1  <-  lanelet #13 (subtype='road'), width 3.5 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.5, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_id", '13'))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelets_14_13')
    road_1.add_type(xodr.RoadType.town, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    odr.add_road(road_1)

    # No adjust_roads_and_lanes() call: geometry is already fixed to the input coordinates, and every road and lane link was resolved from the lanelet topology rather than re-derived from geometry.
    return odr


if __name__ == "__main__":
    build().write_xml('two_way.xodr')
