"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/uses_helpers.py
sha256:  68a94a5d431458a805d2f24ff0d0ae9de317a62bd023057c76952ba8ebe3ece4
summary: 2/2 lanelets converted, 1 roads, 2 lanes
notices: 2 info(s)
    LL2ODR-I305: resolved 'builders' from builders.py beside the input and interpreted it; the converted map depends on that file too
    LL2ODR-I305: resolved 'helpers' from __init__.py beside the input and interpreted it; the converted map depends on that file too

Run this file to write uses_helpers.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/uses_helpers.py."""
    odr = xodr.OpenDrive('uses_helpers', revMajor='1', revMinor='5')

    # ---- road 1  <-  lanelet #14, #7 -----------------------------------
    # reference line: 1 geometry record(s), length 20 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(20.0), 0.0, 6.0, 0.0, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #14 (subtype='road'), width 3 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.0, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_id", '14'))
    lane_1_0_m1.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_1_0.add_right_lane(lane_1_0_m1)
    # lane -2  <-  lanelet #7 (subtype='road'), width 3 m (constant)
    lane_1_0_m2 = xodr.Lane(lane_type=xodr.LaneType.driving, a=3.0, soffset=0.0)
    lane_1_0_m2.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.none))
    lane_1_0_m2.add_userdata(xodr.UserData("lanelet2_id", '7'))
    lane_1_0_m2.add_userdata(xodr.UserData("lanelet2_subtype", 'road'))
    ls_1_0.add_right_lane(lane_1_0_m2)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelets_14_7')
    road_1.add_type(xodr.RoadType.unknown, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    odr.add_road(road_1)

    # No adjust_roads_and_lanes() call: geometry is already fixed to the input coordinates, and every road and lane link was resolved from the lanelet topology rather than re-derived from geometry.
    return odr


if __name__ == "__main__":
    build().write_xml('uses_helpers.xodr')
