"""Generated by opendrive_transpiler. Do not edit if you intend to regenerate.

source:  tests/fixtures/with_projector.py
sha256:  1f40d8c8db756d41e40719cc646ca5c42f8b0d542f6a7d1467b5dcf173c52ed8
summary: 1/1 lanelets converted, 1 roads, 1 lanes, 1 regulatory elements skipped
notices: 1 info(s)
    LL2ODR-I902: 1 regulatory element(s) recognised (TrafficLight); signals and priorities are not converted yet
note:    geoReference derived from utm projector at lat=49.0, lon=8.4

Run this file to write with_projector.xodr. Requires scenariogeneration:
    pip install "opendrive-transpiler[emit]"
"""

from scenariogeneration import xodr


def build() -> xodr.OpenDrive:
    """Build the OpenDRIVE model transpiled from tests/fixtures/with_projector.py."""
    odr = xodr.OpenDrive('with_projector', revMajor='1', revMinor='5', geo_reference='+proj=utm +zone=32 +north +x_0=43885.40413814678 +y_0=-5427629.203876308 +datum=WGS84 +units=m +no_defs')

    # ---- road 1  <-  lanelet #30 ---------------------------------------
    # reference line: 1 geometry record(s), length 12.0416 m
    pv_1 = xodr.PlanView()
    pv_1.add_fixed_geometry(xodr.Line(12.041594578792296), 0.0, 0.0, 0.08314123188844123, s=0.0)

    lanes_1 = xodr.Lanes()

    # lane section 0 at s = 0 m
    center_1_0 = xodr.Lane(a=0.0)
    center_1_0.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.solid, width=0.12))
    ls_1_0 = xodr.LaneSection(0.0, center_1_0)
    # lane -1  <-  lanelet #30 (subtype='road'), width 1.99309 m (constant)
    lane_1_0_m1 = xodr.Lane(lane_type=xodr.LaneType.driving, a=1.9930915164897594, soffset=0.0)
    lane_1_0_m1.add_roadmark(xodr.RoadMark(xodr.RoadMarkType.broken, width=0.12, length=3.0, space=6.0))
    ls_1_0.add_right_lane(lane_1_0_m1)
    lanes_1.add_lanesection(ls_1_0)

    road_1 = xodr.Road(1, pv_1, lanes_1, name='lanelet_30')
    road_1.add_type(xodr.RoadType.unknown, 0.0)
    road_1.add_elevation(0.0, 0.0, 0.0, 0.0, 0.0)
    odr.add_road(road_1)

    # Geometry is already fixed to the input coordinates, so this only derives lane links; it will not move anything.
    odr.adjust_roads_and_lanes()
    return odr


if __name__ == "__main__":
    build().write_xml('with_projector.xodr')
